name: chatup
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  video_player: ^2.10.0
  camera: ^0.11.2
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  file_picker: ^10.2.1
  emoji_picker_flutter: ^3.0.0
  flutter_sound: ^9.2.13+2
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# This key is corrected from 'flutter_icons' to 'flutter_launcher_icons'
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo1.png"
    background_color: "#FFFFFF" # <-- Replace with a real hex color code
    theme_color: "#FFFFFF"      # <-- Replace with a real hex color code
  windows:
    generate: true
    image_path: "assets/images/logo1.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    # Ensure this file exists in your project. If you only use logo1.png, you can remove this.
    - "assets/images/logo.png"
    - "assets/images/logo1.png" # Added this to ensure the icon is included in the app assets
